### ISSUE TITLE
Script throws error when run on a Raspberry Pi

### ISSUE THREAD

**Issue by krishnaglick** [wcrasta/SWA-Scraper#11]
I saw this on reddit and wanted to give it a try, so I installed what was needed and ran it as below.

`python3 app.py --depart MCO --arrive PDX --departure-date 07/17 --passengers 1 --desired-total 250 --interval 30 --one-way`

However I get this issue when it runs. Does Selenium require Chrome or something?

```
Traceback (most recent call last):
  File "app.py", line 204, in <module>
    main()
  File "app.py", line 24, in main
    scrape(args)
  File "app.py", line 92, in scrape
    browser = webdriver.PhantomJS()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x76a9d550>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 173, in __del__
    self.stop()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 145, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
```

**Comment by wcrasta** [comment]
Hi @krishnaglick,
Selenium shouldn't need Chrome; rather, my code uses PhantomJS, which is a different browser. Make sure you have PhantomJS installed and in the right place. This [StackOverflow post](https://stackoverflow.com/questions/37004635/python-selenium-exception-attributeerror-service-object-has-no-attribute-pr) refers to a similar issue, but with Chrome. See if you can do something similar for PhantomJS.
